version: '3.8'

services:
  spring-boot-app:
    image: maxbussinesssolutions/spring-boot-application:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
