version: '3'
services:
  springboot-app:
    image: maxbussinesssolutions/my-spring-boot-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - pg

  pg:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: maxcrackers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Max@0607
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
